### ISSUE TITLE
[Sendgrid UI] Style email template 

### ISSUE THREAD

**Issue by mziyambi** [MetropolitanTransportationCommission/ptap-webapp#36]
Similar to however we do the main UI?
I have a sample page at localhost:3000/email.html so you can see how I'm building the template. Wherever there are names like primary_firstname, those are getting replaced by the actual person's info when the email gets sent.

**Comment by mziyambi** [comment]
Oh, on simpleForm branch

**Comment by gilbertfrausto** [comment]
Where can I find the template you were working on?
